name: zitadel
version: 3.2.0
description: >-
  Dart package for ZITADEL relatet matters. Contains the compiled grpc service
  clients to access the ZITADEL API.

repository: https://github.com/smartive/zitadel-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  fixnum: ^1.0.0
  grpc: ^5.0.0
  http: ^1.0.0
  jose: ^0.3.2
  protobuf: ^5.1.0
dev_dependencies:
  build_runner: ^2.4.4
  code_builder:
  dart_style:
  lints: ^6.0.0
  path: ^1.9.0
  test: ^1.21.6
