name: zitadel
version: 0.0.0-dev
description: >-
  Dart package for Zitadel relatet matters. Contains the compiled grpc (client and server)
  parts for further extension.
repository: https://github.com/caos/zitadel-dart
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  grpc: ^3.0.0
  http: ^0.13.2
  jose: ^0.3.2
  protobuf: ^2.0.0

dev_dependencies:
  test: ^1.17.3
